title: timfether.com
email: tim@timfether.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.timfether.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: timfether
repository: timfether/timfether.github.io

# Build settings
markdown: kramdown
theme: minima

plugins:
  - jekyll-redirect-from